services:
  gestor-usuarios:
    build:
      context: ./back
      dockerfile: Dockerfile
    image: proyplus/gestor-usuarios:latest
    container_name: gestor-usuarios
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
      SWAGGER_UI_ENABLED: ${SWAGGER_UI_ENABLED:-true}
    ports:
      - "${API_PORT:-8080}:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  web-angular:
    build:
      context: ./front
      dockerfile: Dockerfile
    image: proyplus/web-angular:latest
    container_name: web-angular
    depends_on:
      - gestor-usuarios
    env_file:
      - .env
    # ðŸ‘‡ Publica el puerto 80 del contenedor (Nginx) en el puerto que elijas del host (ej. 80 o 4200)
    ports:
      - "${WEB_PORT:-80}:80"
    restart: unless-stopped
