version: "3.9"

services:
  gestor-usuarios:
    build:
      context: ./back
      dockerfile: Dockerfile
    image: proyplus/gestor-usuarios:latest
    container_name: gestor-usuarios
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SWAGGER_UI_ENABLED: "true"  # habilita o no el swagger
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
 
  web-angular:
    build:
      context: ./front
      dockerfile: Dockerfile
    image: proyplus/web-angular:latest
    container_name: web-angular
    depends_on:
      - gestor-usuarios
    ports:
      - "4200:4200"             
    restart: unless-stopped